import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import Header from "../components/Header";
import Footer from "../components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "ImpactAcross",
//   description: "Generated by next app",
// };

export const viewport = {
  themeColor: "#209747",
};

export const metadata = {
  metadataBase: new URL("https://impactacross.com"),
  title: {
    default: "ImpactAcross Consulting",
    template: "%s | ImpactAcross"
  },
  description: "ImpactAcross is a dynamic development research and consultancy firm committed to transforming lives and systems across Africa. We specialize in delivering high-quality research, policy analysis, program design, monitoring & evaluation (M&E), capacity building, and strategic advisory services to NGOs, governments, development agencies, and the private sector.",
  keywords: ["impactacross", "consultancy", "development", "sustainability", "reasearch"],
  authors: [{ name: "Ketsebaot Ertumo", url: "https://ketsebaot.vercel.app" }],
  icons: {
    icon: 'https://res.cloudinary.com/dq6mvqivd/image/upload/v1751620900/ImpactAcross/images/qfnpvklxk1dhiprl71yq.jpg',
    apple: 'https://res.cloudinary.com/dq6mvqivd/image/upload/v1751620900/ImpactAcross/images/qfnpvklxk1dhiprl71yq.jpg',
  },
  openGraph: {
    title: "ImpactAcross Consulting",
    description: "ImpactAcross is a dynamic development research and consultancy firm committed to transforming lives and systems across Africa. We specialize in delivering high-quality research, policy analysis, program design, monitoring & evaluation (M&E), capacity building, and strategic advisory services to NGOs, governments, development agencies, and the private sector.",
    url: "https://impactacross.com",
    siteName: "ImpactAcross Consulting",
    images: [
      {
        url: "https://res.cloudinary.com/dq6mvqivd/image/upload/v1751620900/ImpactAcross/images/qfnpvklxk1dhiprl71yq.jpg",
        width: 1200,
        height: 630,
        alt: "ImpactAcross Consulting",
        type: "image/jpg"
      },
    ],
    locale: "en_US",
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "ImpactAcross Consulting",
    description: "ImpactAcross is a dynamic development research and consultancy firm committed to transforming lives and systems across Africa. We specialize in delivering high-quality research, policy analysis, program design, monitoring & evaluation (M&E), capacity building, and strategic advisory services to NGOs, governments, development agencies, and the private sector.",
    images: [
      {
        url: "https://res.cloudinary.com/dq6mvqivd/image/upload/v1751620900/ImpactAcross/images/qfnpvklxk1dhiprl71yq.jpg",
        width: 1200,
        height: 630,
        alt: "ImpactAcross Consulting",
        type: "image/jpg"
      },
    ],
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
        style={{ fontFamily: "var(--dynamic-font-family)" }}
      >
        <Header />

        <main className="flex-1">
          {children}
        </main>

        <Footer />

        <Toaster position="top-center" />
      </body>
    </html>
  );
}

